{
  "openapi": "3.0.0",
  "info": {
	"title": "Chaster",
	"description": "Chaster Public API\n\nAPI documentation: [https://docs.chaster.app/api-introduction](https://docs.chaster.app/api-introduction)\n",
	"version": "0.11.2",
	"contact": {}
  },
  "tags": [],
  "servers": [
	{
	  "url": "https://api.chaster.app"
	}
  ],
  "components": {
	"securitySchemes": {
	  "bearer": {
		"scheme": "bearer",
		"bearerFormat": "JWT",
		"type": "http"
	  },
	  "oauth2": {
		"type": "oauth2",
		"flows": {
		  "authorizationCode": {
			"authorizationUrl": "https://sso.chaster.app/auth/realms/app/protocol/openid-connect/auth",
			"tokenUrl": "https://sso.chaster.app/auth/realms/app/protocol/openid-connect/token",
			"refreshUrl": "https://sso.chaster.app/auth/realms/app/protocol/openid-connect",
			"scopes": {
			  "profile": "Profile",
			  "email": "Email",
			  "locks": "Locks",
			  "shared_locks": "SharedLocks",
			  "keyholder": "Keyholder",
			  "messaging": "Messaging",
			  "developer": "Developer"
			}
		  }
		}
	  },
	  "clientId": {
		"type": "apiKey",
		"in": "header",
		"name": "X-Chaster-Client-Id",
		"description": "Your application id"
	  },
	  "clientSecret": {
		"type": "apiKey",
		"in": "header",
		"name": "X-Chaster-Client-Secret",
		"description": "Your application secret key"
	  }
	}
  },
  "paths": {
	"/files/upload": {
	  "post": {
		"operationId": "StorageController_uploadFiles",
		"summary": "Upload attachments",
		"description": "Upload attachments and get an attachment token to be used in messaging and posts\n\nThe attachment token expires after one hour.",
		"tags": [
		  "Files"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/shared-locks": {
	  "get": {
		"operationId": "SharedLockController_findAll",
		"summary": "Find all user shared locks",
		"description": "Returns a list of all user shared locks",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "post": {
		"operationId": "SharedLockController_create",
		"summary": "Create a shared lock",
		"description": "Creates a shared lock",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/shared-locks/{sharedLockId}": {
	  "get": {
		"operationId": "SharedLockController_findOne",
		"summary": "Find a shared lock by id",
		"description": "Finds a shared lock by id",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "put": {
		"operationId": "SharedLockController_update",
		"summary": "Update a shared lock",
		"description": "Updates a shared lock",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/shared-locks/{sharedLockId}/archive": {
	  "post": {
		"operationId": "SharedLockController_archive",
		"summary": "Archive a shared lock",
		"description": "Archives a shared lock",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks": {
	  "get": {
		"operationId": "LockController_findAll",
		"summary": "Get user locks",
		"description": "Returns a list of all user locks\n\nBy default, only active locks are returned.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "post": {
		"operationId": "LockCreationController_create",
		"summary": "Create a lock",
		"description": "Creates a personal lock. To create a lock, you must first create\na combination by using the combination endpoints, and then provide its identifier.",
		"tags": [
		  "Lock Creation"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}": {
	  "get": {
		"operationId": "LockController_findOne",
		"summary": "Get a lock by id",
		"description": "Returns a lock by id",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/archive": {
	  "post": {
		"operationId": "LockController_archive",
		"summary": "Archive a lock",
		"description": "Archives a lock as a wearer. A wearer can archive its own lock:\n<ul>\n<li>If the lock is running (status `locked`), the lock will become deserted (status `deserted`),\nwith no possibility of going back.</li>\n<li>If the lock is unlocked, the lock will simply be archived.</li>\n</ul>",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/archive/keyholder": {
	  "post": {
		"operationId": "LockController_archiveKeyholder",
		"summary": "Archive a lock as a keyholder",
		"description": "Archives a lock as a keyholder. Keyholders can use this endpoint to archive unlocked locks.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/update-time": {
	  "post": {
		"operationId": "LockController_updateTime",
		"summary": "Update lock duration",
		"description": "Adds or removes duration to a lock. Keyholders can add or remove time, while wearers can only add time.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/freeze": {
	  "post": {
		"operationId": "LockController_setFreeze",
		"summary": "Freeze a lock",
		"description": "Freezes a lock. Keyholders can use this endpoint to freeze wearer's locks.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/unlock": {
	  "post": {
		"operationId": "LockController_unlock",
		"summary": "Unlock a lock",
		"description": "Unlocks a lock. For wearers, the lock must respect certain constraints so that it can be unlocked.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/settings": {
	  "post": {
		"operationId": "LockController_setSettings",
		"summary": "Update lock settings",
		"description": "Update locks settings. Only the keyholder can update lock settings.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/max-limit-date": {
	  "post": {
		"operationId": "LockController_setMaxLimitDate",
		"summary": "Increase the max limit date",
		"description": "Increase the max limit date. Only the wearer can increase the limit.",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/combination": {
	  "get": {
		"operationId": "LockController_combination",
		"summary": "Find a lock combination",
		"description": "Finds a lock combination",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/history": {
	  "post": {
		"operationId": "LockController_getLockHistory",
		"summary": "Return lock history",
		"description": "Returns a list of action logs",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/public-locks/{sharedLockId}": {
	  "get": {
		"operationId": "PublicLockController_findOne",
		"summary": "Find a public shared lock",
		"description": "Finds a public shared lock",
		"tags": [
		  "Public Locks"
		]
	  }
	},
	"/public-locks/images/{sharedLockId}": {
	  "get": {
		"operationId": "PublicLockController_getSharedLockImage",
		"summary": "Generate a shared lock image",
		"description": "Generates an image illustrating the shared lock, to publish it on forums or social networks.",
		"tags": [
		  "Public Locks"
		],
		"security": [
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/public-locks/search": {
	  "post": {
		"operationId": "PublicLockController_search",
		"summary": "Search for locks",
		"description": "Search for locks",
		"tags": [
		  "Public Locks"
		]
	  }
	},
	"/keyholder/wearers": {
	  "get": {
		"operationId": "KeyholderController_getKeyholderWearers",
		"summary": "Return all locked users",
		"description": "Returns a list of locked users",
		"tags": [
		  "Keyholder"
		],
		"security": [
		  {
			"oauth2": [
			  "keyholder"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/explore/categories": {
	  "get": {
		"operationId": "ExploreCategoryController_findAll",
		"summary": "Find Explore page locks",
		"description": "Returns the locks of the Explore page",
		"tags": [
		  "Public Locks"
		]
	  }
	},
	"/locks/user/{userId}": {
	  "get": {
		"operationId": "LockVisitorController_getUserLocks",
		"summary": "Return the public locks of a user",
		"description": "Returns the public locks of a user",
		"tags": [
		  "Profile"
		]
	  }
	},
	"/combinations/image": {
	  "post": {
		"operationId": "CombinationController_uploadImage",
		"summary": "Upload a combination image",
		"description": "Uploads an image and stores the combination. Once the image is uploaded,\nit cannot be recovered without being associated with a lock. To retrieve\nthe combination, refer to the endpoint `/locks/{lockId}/combination` to\nget the image URL.\n\nIf the combination is not associated with a lock, it expires after one hour.",
		"tags": [
		  "Combinations"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/combinations/code": {
	  "post": {
		"operationId": "CombinationController_createCode",
		"summary": "Create a code combination",
		"description": "Creates and stores the code combination. Once the code is sent, it cannot\nbe recovered without being associated with a lock. To retrieve the\ncombination, refer to the endpoint `/locks/{lockId}/combination` to get\nthe code.\n\nIf the combination is not associated with a lock, it expires after one hour.",
		"tags": [
		  "Combinations"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/extensions": {
	  "get": {
		"operationId": "ExtensionController_getExtensions",
		"summary": "Get the list of extensions",
		"description": "Returns the list of all extensions in memory",
		"tags": [
		  "Extensions"
		]
	  }
	},
	"/locks/{lockId}/extensions/{extensionId}": {
	  "get": {
		"operationId": "LockExtensionController_getLockInfoFromExtension",
		"summary": "Get information from an extension for a given lock",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/{lockId}/extensions/{extensionId}/action": {
	  "post": {
		"operationId": "LockExtensionController_triggerAction",
		"summary": "Trigger an action for a lock extension",
		"description": "Triggers an action in a lock extension",
		"tags": [
		  "Locks"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/locks/shared-locks/{sharedLockId}/extensions": {
	  "put": {
		"operationId": "SharedLockExtensionController_setSharedLockExtensions",
		"summary": "Set shared lock extensions",
		"tags": [
		  "Shared Locks"
		],
		"security": [
		  {
			"oauth2": [
			  "shared_locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/extensions/temporary-opening/{lockId}/combination": {
	  "get": {
		"operationId": "TemporaryOpeningExtensionController_getCombination",
		"summary": "Get a lock combination",
		"description": "Returns the lock combination\n\nThis endpoint only works if the lock is temporarily unlocked by the temporary opening extension",
		"tags": [
		  "Extensions - Temporary Opening"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "post": {
		"operationId": "TemporaryOpeningExtensionController_setCombination",
		"summary": "Set the new combination",
		"description": "Updates the lock combination\n\nThis endpoint only works if the lock is temporarily unlocked by the temporary opening extension",
		"tags": [
		  "Extensions - Temporary Opening"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/extensions/verification-picture/{lockId}/submit": {
	  "post": {
		"operationId": "VerificationPictureExtensionController_submitPicture",
		"summary": "Submit a verification picture",
		"description": "Uploads a new verification picture\n\nA user can upload a picture only if there is an existing request.",
		"tags": [
		  "Extensions - Verification Picture"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/extensions/verification-picture/{lockId}/history": {
	  "get": {
		"operationId": "VerificationPictureExtensionController_getHistory",
		"summary": "Get the history of verification pictures",
		"description": "Returns the history of verification pictures",
		"tags": [
		  "Extensions - Verification Picture"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/public-locks/{sharedLockId}/create-lock": {
	  "post": {
		"operationId": "LockCreationController_createLockFromSharedLock",
		"summary": "Create a lock from a shared lock",
		"description": "Creates a lock from a shared lock. To create a lock, you must first\ncreate a combination and then provide its identifier.",
		"tags": [
		  "Lock Creation"
		],
		"security": [
		  {
			"oauth2": [
			  "locks"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/settings": {
	  "get": {
		"operationId": "SettingsController_getAppSettings",
		"summary": "Get app settings",
		"tags": [
		  "Settings"
		]
	  }
	},
	"/users/profile/by-id/{userId}": {
	  "get": {
		"operationId": "ProfileController_getUserById",
		"summary": "Find a user by id",
		"tags": [
		  "Profile"
		]
	  }
	},
	"/users/profile/{username}": {
	  "get": {
		"operationId": "ProfileController_getUser",
		"summary": "Find a user profile",
		"tags": [
		  "Profile"
		]
	  }
	},
	"/users/profile/{username}/details": {
	  "get": {
		"operationId": "ProfileController_getUserProfile",
		"summary": "Find a user profile with details",
		"tags": [
		  "Profile"
		]
	  }
	},
	"/session-offer/lock/{lockId}": {
	  "post": {
		"operationId": "SessionOfferController_createKeyholdingOffer",
		"summary": "Create a keyholding offer",
		"description": "Allows the wearer to send a keyholding request to another user.",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "locks"
			]
		  }
		]
	  }
	},
	"/session-offer/token/{offerToken}/accept": {
	  "get": {
		"operationId": "SessionOfferController_acceptKeyholdingRequest",
		"summary": "Accept a keyholding request",
		"description": "Accepts a keyholding request from a wearer. By accepting the request, you will become the keyholder. The `offerToken` parameter can be found in the `LockForPublic` object, if the user has enabled this option when creating the lock.",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "keyholder"
			]
		  }
		]
	  }
	},
	"/session-offer/lock/{lockId}/status": {
	  "get": {
		"operationId": "SessionOfferController_getOfferRequestStatus",
		"summary": "Return a list of keyholding offers",
		"description": "Returns a list of keyholding offers",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "locks"
			]
		  }
		]
	  }
	},
	"/session-offer/token/{offerToken}": {
	  "get": {
		"operationId": "SessionOfferController_getLockKeyholdingRequest",
		"summary": "Retrive public information of a lock",
		"description": "Retrieves public information of the lock for the visitor who received a keyholding request link",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/session-offer/{sessionRequestId}": {
	  "post": {
		"operationId": "SessionOfferController_validateOfferRequest",
		"summary": "Accept or reject a keyholding offer from a wearer",
		"description": "Accepts or reject a keyholding offer sent directly by a wearer",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "keyholder"
			]
		  }
		]
	  }
	},
	"/session-offer/{sessionRequestId}/archive": {
	  "get": {
		"operationId": "SessionOfferController_archiveKeyholdingOffer",
		"summary": "Archive a keyholding offer",
		"description": "Archives a keyholding offer. If the offer is pending, it cancels the keyholding offer.",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "locks"
			]
		  }
		]
	  }
	},
	"/session-offer/requests": {
	  "get": {
		"operationId": "SessionOfferController_getKeyholderRequests",
		"summary": "Return keyholding offers from wearers",
		"description": "Returns keyholding offers from wearers",
		"tags": [
		  "Session Offer"
		],
		"security": [
		  {
			"bearer": []
		  },
		  {
			"oauth2": [
			  "keyholder"
			]
		  }
		]
	  }
	},
	"/auth/profile/update": {
	  "get": {
		"operationId": "AuthMeController_meEdit",
		"summary": "Update profile from the authentication server",
		"tags": [
		  "Profile"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/auth/profile": {
	  "get": {
		"operationId": "AuthMeController_me",
		"summary": "Get logged user information",
		"tags": [
		  "Profile"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations": {
	  "get": {
		"operationId": "MessagingController_getConversations",
		"summary": "Find a list of conversations",
		"description": "Finds a list of conversations",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "post": {
		"operationId": "MessagingController_createConversation",
		"summary": "Create a conversation",
		"description": "Creates a conversation",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations/by-user/{userId}": {
	  "get": {
		"operationId": "MessagingController_getConversationByUserId",
		"summary": "Find conversation by user id",
		"description": "Finds a conversation by user id",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations/{conversationId}": {
	  "post": {
		"operationId": "MessagingController_sendMessage",
		"summary": "Add a new message in a conversation",
		"description": "Updates a conversation",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  },
	  "get": {
		"operationId": "MessagingController_getConversation",
		"summary": "Find a conversation",
		"description": "Finds a conversation",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations/{conversationId}/status": {
	  "put": {
		"operationId": "MessagingController_setConversationStatus",
		"summary": "Set a conversation status",
		"description": "Updates a conversation status",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations/{conversationId}/unread": {
	  "put": {
		"operationId": "MessagingController_setConversationUnread",
		"summary": "Set a conversation unread status",
		"description": "Updates a conversation unread status",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/conversations/{conversationId}/messages": {
	  "get": {
		"operationId": "MessagingController_getMessages",
		"summary": "Find messages in a conversation",
		"description": "Finds messages in a conversation",
		"tags": [
		  "Messaging"
		],
		"security": [
		  {
			"oauth2": [
			  "messaging"
			]
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/users/badge/count": {
	  "get": {
		"operationId": "UserBadgeController_getUserBadgeCount",
		"summary": "Get the user badge count",
		"description": "Returns the user badge count",
		"tags": [
		  "Profile"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	},
	"/reports": {
	  "post": {
		"operationId": "ReportController_createReport",
		"summary": "Create a report",
		"description": "Create a report",
		"tags": [
		  "Reports"
		],
		"security": [
		  {
			"oauth2": []
		  },
		  {
			"bearer": []
		  }
		]
	  }
	}
  }
}